# Generated by Django 4.1.7 on 2023-05-02 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_categoria_alter_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 18, 2, 2, 839248)),
        ),
    ]
